### PR TITLE
Added tppAdvisorDetail to Applicant; Added tppApplicationid to Application

### PR DESCRIPTION
**Pull request by olegkovalov**

### CODE REVIEW

**Review by rolfwagner — COMMENTED** [review]
Hi Oleg, thank you. 
tppAdvisorDetails is fine for me. 

Could you please add more detail (description) to the tppId? Is it set by the TPP, allocated by the FI or maybe previously agreed somehow? Why is it needed anyway, as for every call the TPP is authenticated to the FI?

**Comment by pascalstockner** [comment]
Hi Rolf 
It is a request from Valiant and CS that we can also deposit our own Order ID. This should simplify the communication between FI and TPP.

**Comment by rolfwagner** [comment]
> Hi Rolf
> It is a request from Valiant and CS that we can also deposit our own Order ID. This should simplify the communication between FI and TPP.

You mean TPP ID (not Order ID)? Please let me know, how is defining this TPPID (TPP of FI). Or does it differ?

**Comment by pascalstockner** [comment]
As TPP, we also designate our orders with an ID. We would like to be able to share this with the FI so that it is clear which order it is in our system in the event of queries. We call the whole OrderID in our system.

**Comment by olegkovalov** [comment]
Updated, @rolfwagner please take a look.

**Review by rolfwagner — APPROVED** [review]
Hi Oleg & Pascal - now it fits very well. Thank you.

**Pull request merged**
