### PR TITLE
Update mortgageAPI.yaml

### PR DESCRIPTION
**Pull request by rolfwagner**
Requested changes by implementation project Valiant, Axon Ivy, Moneypark.

### CODE REVIEW

**Comment by weber-lars** [comment]
1. GET /mortgages/products, query parameter interestBasis should be deleted (deprecated)
2. GET /mortgages/applications/required-information response, schema validation, $ref in combination
3. constructionQualityType, description, schema validation, $ref in combination
4. stateBuildingType, description, schema validation, $ref in combination
5. product.name is unknow, rename to product.names as required object
6. Party.properties.personList.items.type, schema validation, $ref in combination
7. rename applicationIdRef to applicationIdRef, rename financingRequestIdRef to financingRequestId

**Comment by rolfwagner** [comment]
> 1. GET /mortgages/products, query parameter interestBasis should be deleted (deprecated)
> 2. GET /mortgages/applications/required-information response, schema validation, $ref in combination
> 3. constructionQualityType, description, schema validation, $ref in combination
> 4. stateBuildingType, description, schema validation, $ref in combination
> 5. product.name is unknow, rename to product.names as required object
> 6. Party.properties.personList.items.type, schema validation, $ref in combination
> 7. rename applicationIdRef to applicationIdRef, rename financingRequestIdRef to financingRequestId

1. OK, done
2. OK, done
3. OK, done
4. OK, done
5. OK, done
6. OK, done
7. OK, done

**Review by weber-lars — CHANGES_REQUESTED** [review]
The tppAdvisorDetail should be moved to the root level of the application.
In the current suggestion we could have a tppAdvisorDetail for each debtor which does not match with the business.

The expectation is to to have one tppAdvisorDetail responsible for one dossier/application.

**Review by weber-lars — CHANGES_REQUESTED** [review]
- [ ] I miss the last issue to rename financingRequestIdRef to financingRequestId.

**Comment by rolfwagner** [comment]
> * [ ]  The tppAdvisorDetail should be moved to the root level of the application.
>   In the current suggestion we could have a tppAdvisorDetail for each debtor which does not match with the business.
>   The expectation is to to have one tppAdvisorDetail responsible for one dossier/application.
> * [ ]  tppApplicationid should be renamed to tppApplicationId

Renaming of tppApplicationId and financingRequestId is OK.

@pascalstockner: Do you agree to move tppAdvisorDetail to the root level of application, as you brought this object in together with CS.

**Comment by pascalstockner** [comment]
Hey Rolf

Yes I totally agree with you.

**Pull request merged**
