### PR TITLE
Improved response on application, offer request, order and document creation

### PR DESCRIPTION
**Pull request by olegkovalov**

### CODE REVIEW

**Review by rolfwagner — CHANGES_REQUESTED** [review]
Hi Oleg

I thought we move this change to rls3?
At least it's number 15 in the rls3 roadmap ;-).

Shall I create you an own branch for the future rls3?

Best, Rolf


<html>
<body>


15 | 14.10.2021 | ResponseBody of POST: Include ID | At the moment, POST calls returns a location header with the URI of the created resource. In the Rls3, in the response body, the ID should be returned of the created resource. | low | MP | agreed.Discussed with MP, Axon, CS on 14.10.21
-- | -- | -- | -- | -- | -- | --



</body>
</html>

**Review by rolfwagner — CHANGES_REQUESTED** [review]
Hi Oleg, 

thank you for the PR and the accurate work (type definition is tiptop). 

Please just a descriptiion and example to the id type:
          description: Uuid v4 of the created resource
          example: bcb5d762-8d28-43a2-9398-393b2e8d56ba

Thanks, 
Rolf

**Comment by weber-lars** [comment]
Hi @olegkovalov, hi @rolfwagner

in fact the response is 201 we expect the posted content could successfully be created at the FI.
So we should always expect an ID in the response, right?

How about to add the "required" information to the schema object, e.g.:

    # ---- Resource created response ----
    commonResourceCreatedResponse:
      title: Recource created response
      type: object
      required:
        - id
      properties:
        id:
          $ref: '#/components/schemas/CommonID'

**Comment by rolfwagner** [comment]
> Hi @olegkovalov, hi @rolfwagner
> 
> in fact the response is 201 we expect the posted content could successfully be created at the FI. So we should always expect an ID in the response, right?
> 
> How about to add the "required" information to the schema object, e.g.:
> 
> ```
> # ---- Resource created response ----
> commonResourceCreatedResponse:
>   title: Recource created response
>   type: object
>   required:
>     - id
>   properties:
>     id:
>       $ref: '#/components/schemas/CommonID'
> ```

Good point, makes sense. Ok for me.

**Pull request merged**
