### PR TITLE
Added trancheId, prospect_authorization document type

### PR DESCRIPTION
**Pull request by olegkovalov**
Currently, it is not possible to match tranches in the offer response in case if the customer has multiple tranches with the same product variation.

### CODE REVIEW

**Comment by weber-lars** [comment]
@olegkovalov best thanks for your PR. I understand your requirement.

So you would like to suggest that the TPP is in charge of trancheId and the offerItemId will be generated and returned by the FI.
In such a case there is no further need of the offerItemId and the "offerItem" list should be renamed to "tranches".

How do you think?

**Comment by rolfwagner** [comment]
@olegkovalov @weber-lars Let me know when you have agreed resp. the PR is ok for both. I will then take the final look at it. CS/ Swapnil has already given its approval in today's conference call.

**Comment by Swapnilumrikar** [comment]
I agree with @weber-lars but renaming is nice to have change. As MP and CS are in testing phase, we can only do this change in next iteration. Change from @olegkovalov should be merged.

**Comment by weber-lars** [comment]
Meeting notes 2021-09-24, (CS @Swapnilumrikar , MP @pascalstockner  and AXON @weber-lars )

This PR is okay for all of us. But must be improved in SFTI Rls 3.x because offerItemId will be useless.
In Rls 3.x the offerItemId will be removed.
In Rls 3.x the offerItems will be renamed to tranches.

**Review by rolfwagner — APPROVED** [review]
As agreed with current implementation parties CS, MP, Axon

**Review by rolfwagner — CHANGES_REQUESTED** [review]
Hi Oleg
In your commit, you changed also this:
<<<<<<< tranche-id
                  type: string
                  enum:
                   - proof_of_identity
                   - tax_declaration
                   - proof_of_own_funds
                   - property
                   - property_flyer
                   - property_pictures
                   - proof_of_interest
                   - prospect_authorization
                   - other
                  example: tax_declaration
=======
                  $ref: '#/components/schemas/DocumentType'
>>>>>>> master

Did we spoke about that? As I see this, the new document type should be added to /components/schema/DocumentType only and not to remove the reference and add a shortened enum directly in the request body.  
Let us discuss this tomorrow.

**Comment by olegkovalov** [comment]
@rolfwagner Updated, please take a look.

**Review by rolfwagner — APPROVED** [review]
Thank you Oleg. Fine for me.

**Pull request merged**
