### PR TITLE
issue-28-duration-as-part-of-product-variations

### PR DESCRIPTION
**Pull request by weber-lars**
- duration as optional information
- productVarations as optional information

### CODE REVIEW

**Comment by weber-lars** [comment]
@olegkovalov, @rolfwagner 

Please could you have a look to our minor change.
The change was discussed togehter with Adrian.

Best thanks

**Comment by olegkovalov** [comment]
Hi @weber-lars and @rolfwagner .
As far as product 'SARON' proposed in a different way by providers, we could apply this.
One note. Changes for `ProductVariation` affects `/mortgages/products` and `/mortgages/applications/{applicationId}/financing-requests/{financingRequestId}/offers` API. So it would mean that `rate` is not mandatory for the offer request. Maybe we should split models into `ProductVariation` and `OfferProductVariation` which would contain `rate` as a mandatory field. (not blocking, could be in another PR)

**Review by olegkovalov — APPROVED** [review]

**Comment by rolfwagner** [comment]
ok for me. Thanks Lars.

**Review by michschl — COMMENTED** [review]
Accepted

**Comment by michschl** [comment]
Integrated changes into v2.4.0 branch.

**Pull request merged**
